import React from 'react'
import './Popup.css'

function Popup() {
  return (
    <div className="body">
      <div className="logo">
        <img src="icon-128.png" width="64" />
      </div>
      <div>GitHub tasks</div>
      <ul>
        <li>
          <Switch value={true} />
          <span> Auto review and collapse autogenerated files</span>
        </li>
        <li>
          <Switch value={true} />
          <span> Move out Compare and Open Pull Request buttons</span>
        </li>
      </ul>
    </div>
  )
}

function Switch({value}: {value: boolean}) {
  return (
    <label className="switch">
      <input type="checkbox" checked={value} />
      <span className="slider"></span>
    </label>
  )
}
export default Popup
