import {clickOn, findEl, isClicked, markAsClicked, printLine} from './modules/print'

printLine('Must reload extension for modifications to take effect.')

var isScrollingScriptStarted = false

const autoGenerateFileNames = [
  'Gemfile.lock',
  'yarn.lock',
  'structure.sql',
  'translations/en.ts',
  'schema.graphql',
  'types.ts'
]

// task Auto review and collapse autogenerated files
function onLoad() {
  if (isScrollingScriptStarted) return
  if (!location.href.match(/https:\/\/github.com/)) return

  isScrollingScriptStarted = true

  printLine('Page Tuner automation is running...')

  autoGenerateFileNames.forEach(fileName => {
    const within = findEl(`//div[div[span/a[text()[(contains(.,'${fileName}'))]]]]`)
    if (!within) return
    if (isClicked(within as HTMLElement)) return

    const expandButton = findEl(
      `div/button[@aria-expanded='true'][@aria-label="Toggle diff contents"]`,
      within
    ) as HTMLButtonElement | null

    const reviewedCheckbox = findEl('div/div/div/form/label/input', within) as HTMLInputElement | null

    if (reviewedCheckbox && reviewedCheckbox.checked) {
      markAsClicked(reviewedCheckbox)
      markAsClicked(within as HTMLElement)
    } else if (reviewedCheckbox && !reviewedCheckbox.checked) {
      clickOn(reviewedCheckbox)
      markAsClicked(within as HTMLElement)
    } else {
      clickOn(expandButton)
      markAsClicked(within as HTMLElement)
    }
  })

  isScrollingScriptStarted = false
}

onLoad()

// TODO: find a better way to recheck for page changes
document.addEventListener('scroll', onLoad)
